#!/usr/bin/env python3
r"""Amendment checks (2026-10-07, later pass, after review).

(A) eta does not "break" the generator identity: it reparameterizes it into a
    family V_eta = e^{-(1/2) tanh(eta) A} whose generator depends on eta, so the
    family is not a one-parameter group with respect to additive eta.
(B) Domain qualification: D = d/du is NOT skew-adjoint on L^2[-L,L] without
    boundary conditions, and zero-extended window functions are not a
    translation-invariant space.  [A,D] = -I holds on a COMMON CORE only.
"""
from fractions import Fraction as Fr
import math

def e(x, n=7): return ('%.' + str(n) + 'e') % float(x)

print("="*78)
print("A.  V_eta = e^{-(1/2) tanh(eta) A} is a reparameterised family, not a group")
print("="*78)
print("  dV_eta/d eta = -(1/2) sech^2(eta) * A * V_eta   -> generator DEPENDS on eta")
print("  check the scalar coefficient -(1/2) sech^2(eta) against a difference quotient")
print("  of the exponent c(eta) = -(1/2) tanh(eta):")
def c(et): return -0.5*math.tanh(et)
for et in (0.0, 0.3, 0.6584789, 0.9729551):
    h = 1e-6
    num = (c(et+h) - c(et-h))/(2*h)
    ana = -0.5/math.cosh(et)**2
    print("     eta=%-10.7f  d c/d eta num = %-14s analytic -(1/2)sech^2 = %-14s dev = %s"
          % (et, e(num), e(ana), e(abs(num-ana))))
print("  at eta=0 the coefficient is -1/2, and it decays like sech^2 -> the family")
print("  is NOT generated by a FIXED operator with respect to eta.")

print("\n  group-law failure, exactly:  V_{e1} V_{e2} = V_{e1+e2}  iff")
print("  tanh(e1) + tanh(e2) = tanh(e1+e2)   -- false in general:")
print("   eta1     eta2     tanh e1 + tanh e2   tanh(e1+e2)      difference")
for (e1,e2) in [(0.2,0.3),(0.5,0.5),(0.9729551,0.9729551),(1e-3,1e-3)]:
    lhs = math.tanh(e1)+math.tanh(e2); rhs = math.tanh(e1+e2)
    print("   %-8.6f %-8.6f %-19s %-16s %s" % (e1,e2,e(lhs),e(rhs),e(lhs-rhs)))
print("  CONTROL: the identity DOES hold when either argument is 0 (trivial case):")
print("     e1=0.4, e2=0 : %s vs %s  equal: %s"
      % (e(math.tanh(0.4)+math.tanh(0.0)), e(math.tanh(0.4)),
         abs(math.tanh(0.4)+math.tanh(0.0)-math.tanh(0.4))<1e-15))
print("  CONTROL: in DELTA the group law is exact (that is the point):")
for (d1,d2) in [(0.1,0.15),(0.2,0.3),(0.375,0.375)]:
    print("     d1+d2 = %-8.6f  and the exponent of V is linear in delta -> exact"
          % (d1+d2))
print("\n  WORDING: eta does not 'break' an identity.  The identity")
print("  F(gamma+i delta) = Fhat(e^{-delta A} f)(gamma) is unaffected by relabelling.")
print("  What fails is that the relabelled family has no CONSTANT generator in eta,")
print("  hence obeys no rapidity-addition law.")

print("\n" + "="*78)
print("B.  DOMAIN QUALIFICATION for D = d/du")
print("="*78)
print("  [A,D] = -I was verified on polynomials (checks.py section 5).  Polynomials")
print("  restricted to (-L,L), and C_c^infty(-L,L), are a COMMON CORE for A and D.")
print("  That is the correct scope.  Two things are NOT true on the fixed window:")
print()
L = 0.8
print("  (i) e^{tD} is NOT a unitary group on L^2[-L,L]: translation moves support out.")
print("      a zero-extended window function f, supp f = [-L,L], shifted by t:")
for t in (0.1, 0.4, 0.8, 1.6):
    overlap = max(0.0, 2*L - abs(t))
    print("      t=%-5.2f  supp(f(.-t)) = [%+.2f,%+.2f]  overlap with [-L,L] = %.2f"
          "  mass retained after re-restriction <= %.3f"
          % (t, -L+t, L+t, overlap, overlap/(2*L)))
print("      -> the zero-extended window functions are NOT a translation-invariant space,")
print("         so there is no translation group ON that space to be generated.")
print()
print("  (ii) D with NO boundary condition is not skew-adjoint on L^2[-L,L].")
print("       integration by parts leaves the boundary term [f g]_{-L}^{L}:")
def ipb(f, g, N=20000):
    h = 2*L/N
    s1 = 0.0; s2 = 0.0
    for i in range(N):
        u = -L + (i+0.5)*h
        du = (f(u+1e-6)-f(u-1e-6))/2e-6
        dv = (g(u+1e-6)-g(u-1e-6))/2e-6
        s1 += du*g(u)*h; s2 += f(u)*dv*h
    return s1, s2, f(L)*g(L) - f(-L)*g(-L)
for nm, f, g in [("both vanish at +-L", lambda u: math.cos(math.pi*u/(2*L)),
                                       lambda u: math.cos(math.pi*u/(2*L))**3),
                 ("NEITHER vanishes",   lambda u: 1.0 + u, lambda u: 2.0 - u)]:
    s1, s2, bdry = ipb(f, g)
    print("       %-20s <Df,g> = %-13s <f,Dg> = %-13s sum = %-13s boundary = %s"
          % (nm, e(s1), e(s2), e(s1+s2), e(bdry)))
print("       skew-adjointness needs <Df,g> = -<f,Dg>, i.e. sum = 0, which holds only")
print("       when the boundary term vanishes.  (cf. Bonneau-Faraut-Valent on momentum-")
print("       operator domains; NOT CHECKED here, cited as the reviewer supplied it.)")
print()
print("  CONCLUSION: [A,D] = -I is a relationship on a common core, NOT an identification,")
print("  and NOT a statement about two globally defined generators on one fixed-window")
print("  space.  A is bounded self-adjoint on L^2[-L,L] (||A|| = L); D is the generator of")
print("  translations on L^2(R), where the Sonin/scaling action actually lives.")
print("\nDONE")
